# Generated by Django 5.2.10 on 2026-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product-01', unique=True),
            preserve_default=False,
        ),
    ]
